-- MySQL Script generated by MySQL Workbench
-- 11/19/15 22:46:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema entdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `entdb` ;

-- -----------------------------------------------------
-- Schema entdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `entdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `entdb` ;

-- -----------------------------------------------------
-- Table `entdb`.`ClassificationLevel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entdb`.`ClassificationLevel` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `entdb`.`ClassificationLevel` (
  `ClassificationLevelId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(50) NOT NULL COMMENT '',
  `Level` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`ClassificationLevelId`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `entdb`.`Classification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entdb`.`Classification` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `entdb`.`Classification` (
  `ClassificationId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(50) NOT NULL COMMENT '',
  `ClassificationLevelId` BIGINT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`ClassificationId`)  COMMENT '',
  INDEX `fk_Classification_ClassificationLevel_idx` (`ClassificationLevelId` ASC)  COMMENT '',
  CONSTRAINT `fk_Classification_ClassificationLevel`
    FOREIGN KEY (`ClassificationLevelId`)
    REFERENCES `entdb`.`ClassificationLevel` (`ClassificationLevelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `entdb`.`ClassificationHierarchy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entdb`.`ClassificationHierarchy` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `entdb`.`ClassificationHierarchy` (
  `ClassificationHierarchyId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `ParentId` BIGINT UNSIGNED NOT NULL COMMENT '',
  `ChildId` BIGINT UNSIGNED NOT NULL COMMENT '',
  INDEX `fk_ClassificationHierarchy_Parent_idx` (`ParentId` ASC)  COMMENT '',
  INDEX `fk_ClassificationHierarchy_Child_idx` (`ChildId` ASC)  COMMENT '',
  PRIMARY KEY (`ClassificationHierarchyId`)  COMMENT '',
  CONSTRAINT `fk_ClassificationHierarchy_Parent`
    FOREIGN KEY (`ParentId`)
    REFERENCES `entdb`.`Classification` (`ClassificationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClassificationHierarchy_Child`
    FOREIGN KEY (`ChildId`)
    REFERENCES `entdb`.`Classification` (`ClassificationId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `entdb`.`Picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entdb`.`Picture` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `entdb`.`Picture` (
  `PictureId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `FileName` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`PictureId`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `entdb`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entdb`.`Person` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `entdb`.`Person` (
  `PersonId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `FirstName` VARCHAR(50) NOT NULL COMMENT '',
  `MiddleInitial` VARCHAR(1) NOT NULL COMMENT '',
  `LastName` VARCHAR(50) NOT NULL COMMENT '',
  `Suffix` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`PersonId`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `entdb`.`MethodOfCapture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entdb`.`MethodOfCapture` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `entdb`.`MethodOfCapture` (
  `MethodOfCaptureId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `MethodOfCapture` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`MethodOfCaptureId`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `entdb`.`SpeciesSex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entdb`.`SpeciesSex` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `entdb`.`SpeciesSex` (
  `SpeciesSexId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `Sex` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`SpeciesSexId`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `entdb`.`Specimen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entdb`.`Specimen` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `entdb`.`Specimen` (
  `SpecimenId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `FinderId` BIGINT UNSIGNED NOT NULL COMMENT '',
  `IdentifierId` BIGINT UNSIGNED NOT NULL COMMENT '',
  `OwnerId` BIGINT UNSIGNED NOT NULL COMMENT '',
  `ClassificationId` BIGINT UNSIGNED NOT NULL COMMENT '',
  `PictureId` BIGINT UNSIGNED NOT NULL COMMENT '',
  `MethodOfCaptureId` BIGINT UNSIGNED NOT NULL COMMENT '',
  `ClassificationHierarchyId` BIGINT UNSIGNED NOT NULL COMMENT '',
  `SpeciesSexId` BIGINT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`SpecimenId`, `FinderId`, `IdentifierId`, `OwnerId`, `ClassificationId`, `MethodOfCaptureId`, `ClassificationHierarchyId`, `SpeciesSexId`)  COMMENT '',
  INDEX `fk_Specimen_Finder_idx` (`FinderId` ASC)  COMMENT '',
  INDEX `fk_Specimen_Identifier_idx` (`IdentifierId` ASC)  COMMENT '',
  INDEX `fk_Specimen_Owner_idx` (`OwnerId` ASC)  COMMENT '',
  INDEX `fk_Specimen_Classification_idx` (`ClassificationId` ASC)  COMMENT '',
  INDEX `fk_Specimen_Picture_idx` (`PictureId` ASC)  COMMENT '',
  INDEX `fk_Specimen_MethodOfCapture_idx` (`MethodOfCaptureId` ASC)  COMMENT '',
  INDEX `fk_Specimen_ClassificationHierarchy_idx` (`ClassificationHierarchyId` ASC)  COMMENT '',
  INDEX `fk_Specimen_SpeciesSex1_idx` (`SpeciesSexId` ASC)  COMMENT '',
  CONSTRAINT `fk_Specimen_Person1`
    FOREIGN KEY (`FinderId`)
    REFERENCES `entdb`.`Person` (`PersonId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Specimen_Person2`
    FOREIGN KEY (`IdentifierId`)
    REFERENCES `entdb`.`Person` (`PersonId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Specimen_Person3`
    FOREIGN KEY (`OwnerId`)
    REFERENCES `entdb`.`Person` (`PersonId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Specimen_Classification1`
    FOREIGN KEY (`ClassificationId`)
    REFERENCES `entdb`.`Classification` (`ClassificationId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Specimen_Picture1`
    FOREIGN KEY (`PictureId`)
    REFERENCES `entdb`.`Picture` (`PictureId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Specimen_MethodOfCapture1`
    FOREIGN KEY (`MethodOfCaptureId`)
    REFERENCES `entdb`.`MethodOfCapture` (`MethodOfCaptureId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Specimen_ClassificationHierarchy1`
    FOREIGN KEY (`ClassificationHierarchyId`)
    REFERENCES `entdb`.`ClassificationHierarchy` (`ClassificationHierarchyId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Specimen_SpeciesSex1`
    FOREIGN KEY (`SpeciesSexId`)
    REFERENCES `entdb`.`SpeciesSex` (`SpeciesSexId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
